
    "Farmer's Monument": {
    description: "A monument to the farmers of Sunflower Land",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2284.webp",
    name: "Farmer's Monument",
  },
  "Miner's Monument": {
    description: "A monument to the miners of Sunflower Land",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2285.webp",
    name: "Miner's Monument",
  },
  "Woodcutter's Monument": {
    description: "A monument to the woodcutters of Sunflower Land",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2286.webp",
    name: "Woodcutter's Monument",
  },
  "Teamwork Monument": {
    description: "A monument to the teamwork of Sunflower Land",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2287.webp",
    name: "Teamwork Monument",
  },
 
  "Floor Mirror": {
    description: "A tall mirror perfect for full-body reflections.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2294.webp",
    name: "Floor Mirror",
  },
  "Long Rug": {
    description: "A horizontally long patterned rug to warm up any floor.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2295.webp",
    name: "Long Rug",
  },
  "Garbage Bin": {
    description: "A sturdy bin used for collecting trash.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2296.webp",
    name: "Garbage Bin",
  },
  Wheelbarrow: {
    description: "A classic tool for moving heavy items around the farm.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2297.webp",
    name: "Wheelbarrow",
  },
  "Snail King": {
    description: "Royalty with a slime trail—slow but majestic.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2298.webp",
    name: "Snail King",
  },
  "Reelmaster's Chair": {
    description:
      "A folding chair equipped for serious fishing. Comes with built-in rod holders and fish tales.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2299.webp",
    name: "Reelmaster's Chair",
  },
  "Rat King": {
    description: "A tangled tale of tails and questionable leadership.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2300.webp",
    name: "Rat King",
  },
  "Fruit Tune Box": {
    description: "Plays nothing but berry good music.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2301.webp",
    name: "Fruit Tune Box",
  },
  "Double Bed": {
    description: "A cozy bed that fits two comfortably.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2302.webp",
    name: "Double Bed",
  },
  "Giant Artichoke": {
    description: "The heart of the garden—literally huge Artichoke.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2303.webp",
    name: "Giant Artichoke",
  },
  "Rocket Statue": {
    description:
      "A rocket ready for lift-off—with the whole world on its back!",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2304.webp",
    name: "Rocket Statue",
  },
  "Ant Queen": {
    description: "She rules the dirt—and your crumbs.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2305.webp",
    name: "Ant Queen",
  },
  "Jurassic Droplet": {
    description: "Dino doo, polished and preserved—nature’s weirdest relic.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2306.webp",
    name: "Jurassic Droplet",
  },
  "Giant Onion": {
    description: "It’s big. It’s bold. It will make your whole field cry.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2307.webp",
    name: "Giant Onion",
  },
  "Giant Turnip": {
    description:
      "A massive turnip that stands tall in the field—too big to harvest, but perfect for display.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2308.webp",
    name: "Giant Turnip",
  },
  "Groovy Gramophone": {
    description: "Spins vintage vibes and funky beats.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2309.webp",
    name: "Groovy Gramophone",
  },
  "Wheat Whiskers": {
    description: "A bundle of wheat playfully accompanied by curious mice.",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2310.webp",
    name: "Wheat Whiskers",
  },
  Cheer: {
    description: "Give a cheer to your fellow farmers!",
    decimals: 0,
    attributes: [
      { trait_type: "Purpose", value: "Decoration" },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/765.webp",
    name: "Cheer",
  },
  Trash: {
    description: "A piece of trash",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2291.webp",
    name: "Trash",
  },
  Dung: {
    description: "A piece of dung",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2292.webp",
    name: "Dung",
  },
  Weed: {
    description: "A weed",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2293.webp",
    name: "Weed",
  },
  Anthill: {
    description: "An anthill",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2314.webp",
    name: "Anthill",
  },
  Rat: {
    description: "A rat",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2315.webp",
    name: "Rat",
  },
  Snail: {
    description: "A snail",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2316.webp",
    name: "Snail",
  },
  "Pest Net": {
    description: "A pest net",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2317.webp",
    name: "Pest Net",
  },
  Poseidon: {
    description: "The mythical Poseidon, the god of the sea.",
    decimals: 0,
    attributes: [
      { trait_type: "Boost", value: "Fish" },
      {
        display_type: "boost_number",
        trait_type: "+1 Fish during Autumn",
        value: 1,
      },
      { trait_type: "Tradable", value: "Yes" },
    ],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2318.webp",
    name: "Poseidon",
  },
  Moonfur: {
    description: "A fluffy moonfur",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Moonfur",
  },
  "Legendary Shrine": {
    description: "A legendary shrine that buffs everything!",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Legendary Shrine",
  },
  "Fossil Shell": {
    description: "A fossil shell",
    decimals: 0,
    attributes: [{ trait_type: "Purpose", value: "Decoration" }],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Fossil Shell",
  },
  "Fox Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Fox Shrine",
  },
  "Boar Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Boar Shrine",
  },
  "Hound Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Hound Shrine",
  },
  "Stag Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Stag Shrine",
  },
  "Pet Egg": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Pet Egg",
  },
  Ruffroot: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Ruffroot",
  },
  "Chewed Bone": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Chewed Bone",
  },
  "Heart leaf": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Heart leaf",
  },
  Acorn: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Acorn",
  },
  Meowchi: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Meowchi",
  },
  Burro: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Burro",
  },
  Twizzle: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Twizzle",
  },
  Barkley: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Barkley",
  },
  Mudhorn: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Mudhorn",
  },
  Nibbles: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Nibbles",
  },
  Waddles: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Waddles",
  },
  Ramsey: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Ramsey",
  },
  Dewberry: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Dewberry",
  },
  "Wild Grass": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Wild Grass",
  },
  Ribbon: {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Ribbon",
  },
  "Frost Pebble": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Frost Pebble",
  },
  "Mole Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Mole Shrine",
  },
  "Badger Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Mole Shrine",
  },
  "Collie Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Mole Shrine",
  },
  "Toucan Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Mole Shrine",
  },
  "Sparrow Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Mole Shrine",
  },
  "Moth Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Moth Shrine",
  },
  "Bear Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Bear Shrine",
  },
  "Tortoise Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Tortoise Shrine",
  },
  "Obsidian Shrine": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/?.webp",
    name: "Obsidian Shrine",
  },
  "Ancient Tree": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2702.png",
    name: "Ancient Tree",
  },
  "Sacred Tree": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2703.png",
    name: "Sacred Tree",
  },
  "Refined Iron Rock": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2704.png",
    name: "Refined Iron Rock",
  },
  "Tempered Iron Rock": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2705.png",
    name: "Tempered Iron Rock",
  },
  "Pure Gold Rock": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2706.png",
    name: "Pure Gold Rock",
  },
  "Enchanted Gold Rock": {
    decimals: 0,
    description: "",
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/2707.png",
    name: "Enchanted Gold Rock",
  },
  Biscuit: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Biscuit",
  },
  Cloudy: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Cloudy",
  },
  Butters: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Butters",
  },
  Smokey: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Smokey",
  },
  Flicker: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Flicker",
  },
  Pippin: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Pippin",
  },
  Pinto: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Pinto",
  },
  Roan: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Roan",
  },
  Stallion: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Stallion",
  },
  Bison: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Bison",
  },
  Oxen: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Oxen",
  },
  Peanuts: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Peanuts",
  },
  Pip: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Pip",
  },
  Skipper: {
    description: "",
    decimals: 0,
    attributes: [],
    external_url: "https://docs.sunflower-land.com/getting-started/about",
    image: "../public/erc1155/images/question_mark.png",
    name: "Skipper",
  },
};

