# app/domain/dimensions.py

# Dimensões (largura x altura) de itens que ocupam mais de uma célula no mapa.
# O ponto de ancoragem (coordenadas) é sempre o canto superior esquerdo.
PLACEABLE_DIMENSIONS = {
    # Edifícios
    "Crop Machine": {"width": 6, "height": 4},
    "Greenhouse": {"width": 4, "height": 4},
    "Town Center": {"width": 3, "height": 3},
    "House": {"width": 3, "height": 3},
    "Manor": {"width": 3, "height": 3},
    "Mansion": {"width": 3, "height": 3},
    "Market": {"width": 2, "height": 2},
    "Fire Pit": {"width": 2, "height": 2},
    "Kitchen": {"width": 2, "height": 2},
    "Bakery": {"width": 2, "height": 2},
    "Deli": {"width": 2, "height": 2},
    "Smoothie Shack": {"width": 2, "height": 2},
    "Workbench": {"width": 2, "height": 2},
    "Toolshed": {"width": 2, "height": 2},
    "Warehouse": {"width": 2, "height": 2},
    "Hen House": {"width": 2, "height": 2},
    "Barn": {"width": 3, "height": 2},
    "Compost Bin": {"width": 2, "height": 1},
    "Turbo Composter": {"width": 2, "height": 1},
    "Premium Composter": {"width": 2, "height": 1},

    # Coletáveis Grandes
    "Basic Scarecrow": {"width": 1, "height": 2},
    "Scary Mike": {"width": 1, "height": 2},
    "Laurie the Chuckle Crow": {"width": 1, "height": 2},
    "Nancy": {"width": 1, "height": 2},
    "Kuebiko": {"width": 1, "height": 2},
    "Gnome": {"width": 1, "height": 2},
    "Clementine": {"width": 1, "height": 2},
    "Cobalt": {"width": 1, "height": 2},
    "Blossombeard": {"width": 1, "height": 2},
    "Desert Gnome": {"width": 1, "height": 2},
    "Volcano Gnome": {"width": 1, "height": 2},
    "Time Warp Totem": {"width": 1, "height": 2},
    "Super Totem": {"width": 1, "height": 2},
    "Mushroom House": {"width": 2, "height": 2},
    "Observatory": {"width": 2, "height": 2},
    "Fountain": {"width": 2, "height": 2},
    "Nyon Statue": {"width": 2, "height": 2},
    "Farmer Bath": {"width": 2, "height": 2},
    "Mysterious Head": {"width": 2, "height": 2},
    "Sunflower Statue": {"width": 2, "height": 2},
    "Potato Statue": {"width": 2, "height": 2},
    "Christmas Tree": {"width": 2, "height": 2},
    "Festive Tree": {"width": 2, "height": 2},
    "Wicker Man": {"width": 1, "height": 2},
    "Tiki Totem": {"width": 1, "height": 2},
    "Tunnel Mole": {"width": 1, "height": 2},
    "Rocky the Mole": {"width": 1, "height": 2},
    "Nugget": {"width": 1, "height": 2},
    "Rock Golem": {"width": 1, "height": 2},
    "Genie Lamp": {"width": 1, "height": 2},
    "Heart of Davy Jones": {"width": 2, "height": 2},
    "Kraken Head": {"width": 2, "height": 2},
    "T-Rex Skull": {"width": 2, "height": 2},
}

