# ==============================================================================
#  FISHING DATA
#  A comprehensive dictionary of all fish, their characteristics, and uses.
#  Data is cross-referenced from fishing.ts and config.py.
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. FISHING_DATA: Details for each fish available in the game.
#    - type: The category of the fish.
#    - baits: A list of baits that can be used to catch the fish.
#    - seasons: A list of seasons in which the fish can be caught.
#    - likes: A list of chum items that increase the chance of catching the fish.
#    - used_in: A list of recipes that require this fish as an ingredient.
#    - difficulty: A rating from 1-5 on the catching minigame difficulty.
# ------------------------------------------------------------------------------
FISHING_DATA = {
    # --- Basic Fish ---
    "Anchovy": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["spring", "summer", "autumn", "winter"],
        "likes": ["Carrot", "Egg"],
        "used_in": ["Chowder"],
        "difficulty": None,
    },
    "Butterflyfish": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["summer", "autumn"],
        "likes": ["Sunflower"],
        "used_in": ["Fish Omelette"],
        "difficulty": None,
    },
    "Blowfish": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["winter"],
        "likes": ["Yam"],
        "used_in": ["Seafood Basket"],
        "difficulty": None,
    },
    "Clownfish": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["summer", "winter"],
        "likes": ["Cabbage"],
        "used_in": [],
        "difficulty": None,
    },
    "Sea Bass": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["spring", "autumn"],
        "likes": ["Anchovy"],
        "used_in": [],
        "difficulty": None,
    },
    "Sea Horse": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["spring", "summer"],
        "likes": ["Seaweed"],
        "used_in": [],
        "difficulty": None,
    },
    "Horse Mackerel": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["summer", "winter"],
        "likes": ["Blueberry"],
        "used_in": ["Fish Burger"],
        "difficulty": 1,
    },
    "Halibut": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["spring", "autumn"],
        "likes": ["Anchovy"],
        "used_in": ["Fish n Chips"],
        "difficulty": None,
    },
    "Squid": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["spring", "winter"],
        "likes": ["Eggplant", "Onion"],
        "used_in": ["Fried Calamari"],
        "difficulty": 1,
    },
    "Porgy": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["spring"],
        "likes": ["Yam"],
        "used_in": [],
        "difficulty": None,
    },
    "Muskellunge": {
        "type": "basic",
        "baits": ["Earthworm"],
        "seasons": ["autumn"],
        "likes": ["Turnip"],
        "used_in": [],
        "difficulty": None,
    },

    # --- Advanced Fish ---
    "Red Snapper": {
        "type": "advanced",
        "baits": ["Grub", "Red Wiggler", "Fishing Lure"],
        "seasons": ["spring", "summer", "autumn", "winter"],
        "likes": ["Apple", "Honey"],
        "used_in": ["Gumbo"],
        "difficulty": None,
    },
    "Moray Eel": {
        "type": "advanced",
        "baits": ["Earthworm", "Grub", "Fishing Lure"],
        "seasons": ["summer", "autumn"],
        "likes": ["Gold"],
        "used_in": [],
        "difficulty": None,
    },
    "Olive Flounder": {
        "type": "advanced",
        "baits": ["Earthworm", "Grub", "Fishing Lure"],
        "seasons": ["spring", "autumn"],
        "likes": ["Rhubarb"],
        "used_in": ["Ocean's Olive"],
        "difficulty": None,
    },
    "Napoleanfish": {
        "type": "advanced",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["summer", "autumn"],
        "likes": ["Carrot"],
        "used_in": ["Seafood Basket"],
        "difficulty": None,
    },
    "Surgeonfish": {
        "type": "advanced",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["summer", "autumn"],
        "likes": ["Orange"],
        "used_in": ["Fish Omelette"],
        "difficulty": None,
    },
    "Angelfish": {
        "type": "advanced",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["summer", "winter"],
        "likes": ["Banana"],
        "used_in": ["Sushi Roll"],
        "difficulty": None,
    },
    "Zebra Turkeyfish": {
        "type": "advanced",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["spring", "summer"],
        "likes": ["Beetroot", "Rhubarb"],
        "used_in": [],
        "difficulty": 1,
    },
    "Ray": {
        "type": "advanced",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["spring", "summer"],
        "likes": ["Squid"],
        "used_in": [],
        "difficulty": 1,
    },
    "Hammerhead shark": {
        "type": "advanced",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["summer", "autumn"],
        "likes": ["Iron"],
        "used_in": [],
        "difficulty": 2,
    },
    "Barred Knifejaw": {
        "type": "advanced",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["spring", "summer"],
        "likes": ["Anchovy"],
        "used_in": [],
        "difficulty": 3,
    },
    "Walleye": {
        "type": "advanced",
        "baits": ["Grub"],
        "seasons": ["winter"],
        "likes": ["Broccoli"],
        "used_in": [],
        "difficulty": None,
    },
    "Rock Blackfish": {
        "type": "advanced",
        "baits": ["Grub"],
        "seasons": ["autumn"],
        "likes": ["Onion"],
        "used_in": [],
        "difficulty": None,
    },
    "Tilapia": {
        "type": "advanced",
        "baits": ["Grub"],
        "seasons": ["summer"],
        "likes": ["Zucchini"],
        "used_in": [],
        "difficulty": None,
    },

    # --- Expert Fish ---
    "Tuna": {
        "type": "expert",
        "baits": ["Grub", "Red Wiggler", "Fishing Lure"],
        "seasons": ["spring", "summer", "autumn", "winter"],
        "likes": ["Orange", "Wild Mushroom"],
        "used_in": ["Fermented Fish"],
        "difficulty": None,
    },
    "Mahi Mahi": {
        "type": "expert",
        "baits": ["Grub", "Red Wiggler", "Fishing Lure"],
        "seasons": ["summer", "autumn"],
        "likes": ["Corn"],
        "used_in": [],
        "difficulty": None,
    },
    "Blue Marlin": {
        "type": "expert",
        "baits": ["Grub", "Red Wiggler", "Fishing Lure"],
        "seasons": ["summer", "winter"],
        "likes": ["Wheat"],
        "used_in": [],
        "difficulty": None,
    },
    "Oarfish": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["spring", "winter"],
        "likes": ["Kale"],
        "used_in": [],
        "difficulty": None,
    },
    "Football fish": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["winter"],
        "likes": ["Sunflower"],
        "used_in": [],
        "difficulty": None,
    },
    "Sunfish": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["summer", "autumn"],
        "likes": ["Anchovy"],
        "used_in": ["Seafood Basket"],
        "difficulty": 2,
    },
    "Coelacanth": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["spring", "winter"],
        "likes": ["Cabbage"],
        "used_in": [],
        "difficulty": 2,
    },
    "Parrotfish": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["spring", "summer"],
        "likes": ["Seaweed"],
        "used_in": [],
        "difficulty": None,
    },
    "Whale Shark": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["summer", "winter"],
        "likes": ["Crab", "Fat Chicken"],
        "used_in": [],
        "difficulty": 3,
    },
    "Saw Shark": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["spring", "summer"],
        "likes": ["Red Snapper", "Speed Chicken"],
        "used_in": [],
        "difficulty": 4,
    },
    "White Shark": {
        "type": "expert",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["summer", "winter"],
        "likes": ["Tuna", "Rich Chicken"],
        "used_in": [],
        "difficulty": 4,
    },
    "Cobia": {
        "type": "expert",
        "baits": ["Red Wiggler"],
        "seasons": ["summer"],
        "likes": ["Broccoli"],
        "used_in": [],
        "difficulty": None,
    },
    "Trout": {
        "type": "expert",
        "baits": ["Red Wiggler"],
        "seasons": ["winter"],
        "likes": ["Pepper"],
        "used_in": [],
        "difficulty": None,
    },
    "Weakfish": {
        "type": "expert",
        "baits": ["Red Wiggler"],
        "seasons": ["spring"],
        "likes": ["Artichoke"],
        "used_in": [],
        "difficulty": None,
    },

    # --- Marine Marvels ---
    "Twilight Anglerfish": {
        "type": "marine marvel",
        "baits": ["Red Wiggler", "Grub", "Fishing Lure"],
        "seasons": ["winter", "spring", "summer", "autumn"],
        "likes": ["Sunfish"],
        "used_in": [],
        "difficulty": 5,
    },
    "Starlight Tuna": {
        "type": "marine marvel",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["winter", "spring", "summer", "autumn"],
        "likes": ["Horse Mackerel", "Zebra Turkeyfish"],
        "used_in": [],
        "difficulty": 5,
    },
    "Radiant Ray": {
        "type": "marine marvel",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": ["winter", "spring", "summer", "autumn"],
        "likes": ["Iron"],
        "used_in": [],
        "difficulty": 4,
    },
    "Phantom Barracuda": {
        "type": "marine marvel",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": ["winter", "spring", "summer", "autumn"],
        "likes": ["Squid"],
        "used_in": [],
        "difficulty": 4,
    },
    "Gilded Swordfish": {
        "type": "marine marvel",
        "baits": ["Earthworm", "Red Wiggler", "Fishing Lure"],
        "seasons": ["winter", "spring", "summer", "autumn"],
        "likes": ["Gold"],
        "used_in": [],
        "difficulty": 3,
    },
    
    # --- Chapter Fish (subtype of Marine Marvel) ---
    "Crimson Carp": {
        "type": "chapter",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": [],
        "likes": [],
        "used_in": [],
        "difficulty": None,
    },
    "Battle Fish": {
        "type": "chapter",
        "baits": ["Earthworm", "Grub", "Fishing Lure"],
        "seasons": [],
        "likes": [],
        "used_in": [],
        "difficulty": None,
    },
    "Lemon Shark": {
        "type": "chapter",
        "baits": ["Grub", "Fishing Lure"],
        "seasons": [],
        "likes": [],
        "used_in": [],
        "difficulty": None,
    },
    "Longhorn Cowfish": {
        "type": "chapter",
        "baits": ["Red Wiggler", "Fishing Lure"],
        "seasons": [],
        "likes": [],
        "used_in": [],
        "difficulty": None,
    },
    "Jellyfish": {
        "type": "chapter",
        "baits": ["Grub", "Red Wiggler", "Fishing Lure"],
        "seasons": [],
        "likes": [],
        "used_in": [],
        "difficulty": None,
    },
    "Pink Dolphin": {
        "type": "chapter",
        "baits": ["Grub", "Red Wiggler", "Fishing Lure"],
        "seasons": [],
        "likes": [],
        "used_in": [],
        "difficulty": None,
    },
}