# app/domain/foods.py
"""
Fonte da Verdade para os dados de comidas e outros consumíveis.

Este módulo centraliza todas as informações sobre itens consumíveis,
agrupados pelo local de preparação (Fire Pit, Kitchen, etc.). Os dados
foram extraídos e adaptados do ficheiro 'consumables.ts' do jogo.
"""

CONSUMABLES_DATA = {
    # --- GRUPO FIRE PIT ---
    "Mashed Potato": {
        "name": "Mashed Potato",
        "building": "Fire Pit",
        "experience": 3,
        "cooking_seconds": 30,
        "ingredients": {"Potato": 8},
        "enabled": True    },
    "Pumpkin Soup": {
        "name": "Pumpkin Soup",
        "building": "Fire Pit",
        "experience": 24,
        "cooking_seconds": 180,
        "ingredients": {"Pumpkin": 10},
        "enabled": True    },
    "Reindeer Carrot": {
        "name": "Reindeer Carrot",
        "building": "Fire Pit",
        "experience": 36,
        "cooking_seconds": 300,
        "ingredients": {"Carrot": 5},
        "enabled": True    },
    "Mushroom Soup": {
        "name": "Mushroom Soup",
        "building": "Fire Pit",
        "experience": 56,
        "cooking_seconds": 600,
        "ingredients": {"Wild Mushroom": 5},
        "enabled": True    },
    "Popcorn": {
        "name": "Popcorn",
        "building": "Fire Pit",
        "experience": 200,
        "cooking_seconds": 720,
        "ingredients": {"Sunflower": 100, "Corn": 5},
        "enabled": True    },
    "Bumpkin Broth": {
        "name": "Bumpkin Broth",
        "building": "Fire Pit",
        "experience": 96,
        "cooking_seconds": 1200,
        "ingredients": {"Carrot": 10, "Cabbage": 5},
        "enabled": True    },
    "Cabbers n Mash": {
        "name": "Cabbers n Mash",
        "building": "Fire Pit",
        "experience": 250,
        "cooking_seconds": 2400,
        "ingredients": {"Mashed Potato": 10, "Cabbage": 20},
        "enabled": True    },
    "Boiled Eggs": {
        "name": "Boiled Eggs",
        "building": "Fire Pit",
        "experience": 90,
        "cooking_seconds": 3600,
        "ingredients": {"Egg": 10},
        "enabled": True    },
    "Kale Stew": {
        "name": "Kale Stew",
        "building": "Fire Pit",
        "experience": 400,
        "cooking_seconds": 7200,
        "ingredients": {"Kale": 10},
        "enabled": True    },
    "Kale Omelette": {
        "name": "Kale Omelette",
        "building": "Fire Pit",
        "experience": 1250,
        "cooking_seconds": 12600,
        "ingredients": {"Egg": 40, "Kale": 5},
        "enabled": True    },
    "Gumbo": {
        "name": "Gumbo",
        "building": "Fire Pit",
        "experience": 600,
        "cooking_seconds": 14400,
        "ingredients": {"Potato": 50, "Pumpkin": 30, "Carrot": 20, "Red Snapper": 3},
        "enabled": True    },
    "Rapid Roast": {
        "name": "Rapid Roast",
        "building": "Fire Pit",
        "experience": 300,
        "cooking_seconds": 10,
        "ingredients": {"Magic Mushroom": 1, "Pumpkin": 40},
        "enabled": True    },
    "Fried Tofu": {
        "name": "Fried Tofu",
        "building": "Fire Pit",
        "experience": 400,
        "cooking_seconds": 5400,
        "ingredients": {"Soybean": 15, "Sunflower": 200},
        "enabled": True    },
    "Rice Bun": {
        "name": "Rice Bun",
        "building": "Fire Pit",
        "experience": 2600,
        "cooking_seconds": 18000,
        "ingredients": {"Rice": 2, "Wheat": 50},
        "enabled": True    },
    "Antipasto": {
        "name": "Antipasto",
        "building": "Fire Pit",
        "experience": 3000,
        "cooking_seconds": 10800,
        "ingredients": {"Olive": 2, "Grape": 2},
        "enabled": True    },
    "Pizza Margherita": {
        "name": "Pizza Margherita",
        "building": "Fire Pit",
        "experience": 25000,
        "cooking_seconds": 72000,
        "ingredients": {"Tomato": 30, "Cheese": 5, "Wheat": 20},
        "enabled": True    },
    "Rhubarb Tart": {
        "name": "Rhubarb Tart",
        "building": "Fire Pit",
        "experience": 5,
        "cooking_seconds": 60,
        "ingredients": {"Rhubarb": 3},
        "enabled": True    },
    
    # --- GRUPO KITCHEN ---
    "Sunflower Crunch": {
        "name": "Sunflower Crunch",
        "building": "Kitchen",
        "experience": 50,
        "cooking_seconds": 600,
        "ingredients": {"Sunflower": 300},
        "enabled": True    },
    "Mushroom Jacket Potatoes": {
        "name": "Mushroom Jacket Potatoes",
        "building": "Kitchen",
        "experience": 240,
        "cooking_seconds": 600,
        "ingredients": {"Wild Mushroom": 10, "Potato": 5},
        "enabled": True    },
    "Fruit Salad": {
        "name": "Fruit Salad",
        "building": "Kitchen",
        "experience": 225,
        "cooking_seconds": 1800,
        "ingredients": {"Apple": 1, "Orange": 1, "Blueberry": 1},
        "enabled": True    },
    "Pancakes": {
        "name": "Pancakes",
        "building": "Kitchen",
        "experience": 1000,
        "cooking_seconds": 3600,
        "ingredients": {"Wheat": 10, "Egg": 10, "Honey": 6},
        "enabled": True    },
    "Roast Veggies": {
        "name": "Roast Veggies",
        "building": "Kitchen",
        "experience": 170,
        "cooking_seconds": 7200,
        "ingredients": {"Cauliflower": 15, "Carrot": 10},
        "enabled": True    },
    "Cauliflower Burger": {
        "name": "Cauliflower Burger",
        "building": "Kitchen",
        "experience": 255,
        "cooking_seconds": 10800,
        "ingredients": {"Cauliflower": 15, "Wheat": 5},
        "enabled": True    },
    "Club Sandwich": {
        "name": "Club Sandwich",
        "building": "Kitchen",
        "experience": 170,
        "cooking_seconds": 10800,
        "ingredients": {"Sunflower": 100, "Carrot": 25, "Wheat": 5},
        "enabled": True    },
    "Bumpkin Salad": {
        "name": "Bumpkin Salad",
        "building": "Kitchen",
        "experience": 290,
        "cooking_seconds": 12600,
        "ingredients": {"Beetroot": 20, "Parsnip": 10},
        "enabled": True    },
    "Bumpkin ganoush": {
        "name": "Bumpkin ganoush",
        "building": "Kitchen",
        "experience": 1000,
        "cooking_seconds": 18000,
        "ingredients": {"Eggplant": 30, "Potato": 50, "Parsnip": 10},
        "enabled": True    },
    "Goblin's Treat": {
        "name": "Goblin's Treat",
        "building": "Kitchen",
        "experience": 500,
        "cooking_seconds": 21600,
        "ingredients": {"Pumpkin": 10, "Radish": 20, "Cabbage": 10},
        "enabled": True    },
    "Chowder": {
        "name": "Chowder",
        "building": "Kitchen",
        "experience": 1000,
        "cooking_seconds": 28800,
        "ingredients": {"Beetroot": 10, "Wheat": 10, "Parsnip": 5, "Anchovy": 3},
        "enabled": True    },
    "Bumpkin Roast": {
        "name": "Bumpkin Roast",
        "building": "Kitchen",
        "experience": 2500,
        "cooking_seconds": 43200,
        "ingredients": {"Mashed Potato": 20, "Roast Veggies": 5},
        "enabled": True    },
    "Goblin Brunch": {
        "name": "Goblin Brunch",
        "building": "Kitchen",
        "experience": 2500,
        "cooking_seconds": 43200,
        "ingredients": {"Boiled Eggs": 5, "Goblin's Treat": 1},
        "enabled": True    },
    "Beetroot Blaze": {
        "name": "Beetroot Blaze",
        "building": "Kitchen",
        "experience": 2000,
        "cooking_seconds": 30,
        "ingredients": {"Magic Mushroom": 2, "Beetroot": 50},
        "enabled": True    },
    "Steamed Red Rice": {
        "name": "Steamed Red Rice",
        "building": "Kitchen",
        "experience": 3000,
        "cooking_seconds": 14400,
        "ingredients": {"Rice": 3, "Beetroot": 50},
        "enabled": True    },
    "Tofu Scramble": {
        "name": "Tofu Scramble",
        "building": "Kitchen",
        "experience": 1000,
        "cooking_seconds": 10800,
        "ingredients": {"Soybean": 20, "Egg": 20, "Cauliflower": 10},
        "enabled": True    },
    "Fried Calamari": {
        "name": "Fried Calamari",
        "building": "Kitchen",
        "experience": 1500,
        "cooking_seconds": 18000,
        "ingredients": {"Sunflower": 200, "Wheat": 15, "Squid": 1},
        "enabled": True    },
    "Fish Burger": {
        "name": "Fish Burger",
        "building": "Kitchen",
        "experience": 1300,
        "cooking_seconds": 7200,
        "ingredients": {"Beetroot": 10, "Wheat": 10, "Horse Mackerel": 1},
        "enabled": True    },
    "Fish Omelette": {
        "name": "Fish Omelette",
        "building": "Kitchen",
        "experience": 1500,
        "cooking_seconds": 18000,
        "ingredients": {"Egg": 40, "Surgeonfish": 1, "Butterflyfish": 2},
        "enabled": True    },
    "Ocean's Olive": {
        "name": "Ocean's Olive",
        "building": "Kitchen",
        "experience": 2000,
        "cooking_seconds": 7200,
        "ingredients": {"Olive Flounder": 1, "Olive": 2},
        "enabled": True    },
    "Seafood Basket": {
        "name": "Seafood Basket",
        "building": "Kitchen",
        "experience": 2200,
        "cooking_seconds": 18000,
        "ingredients": {"Blowfish": 2, "Napoleanfish": 2, "Sunfish": 2},
        "enabled": True    },
    "Fish n Chips": {
        "name": "Fish n Chips",
        "building": "Kitchen",
        "experience": 2000,
        "cooking_seconds": 14400,
        "ingredients": {"Fancy Fries": 1, "Halibut": 1},
        "enabled": True    },
    "Sushi Roll": {
        "name": "Sushi Roll",
        "building": "Kitchen",
        "experience": 2000,
        "cooking_seconds": 3600,
        "ingredients": {"Angelfish": 1, "Seaweed": 1, "Rice": 2},
        "enabled": True    },
    "Caprese Salad": {
        "name": "Caprese Salad",
        "building": "Kitchen",
        "experience": 6000,
        "cooking_seconds": 10800,
        "ingredients": {"Cheese": 1, "Tomato": 25, "Kale": 20},
        "enabled": True    },
    "Spaghetti al Limone": {
        "name": "Spaghetti al Limone",
        "building": "Kitchen",
        "experience": 15000,
        "cooking_seconds": 54000,
        "ingredients": {"Wheat": 10, "Lemon": 15, "Cheese": 3},
        "enabled": True    },

    # --- GRUPO BAKERY ---
    "Apple Pie": {
        "name": "Apple Pie",
        "building": "Bakery",
        "experience": 720,
        "cooking_seconds": 14400,
        "ingredients": {"Apple": 5, "Wheat": 10, "Egg": 20},
        "enabled": True    },
    "Orange Cake": {
        "name": "Orange Cake",
        "building": "Bakery",
        "experience": 730,
        "cooking_seconds": 14400,
        "ingredients": {"Orange": 5, "Egg": 30, "Wheat": 10},
        "enabled": True    },
    "Kale & Mushroom Pie": {
        "name": "Kale & Mushroom Pie",
        "building": "Bakery",
        "experience": 720,
        "cooking_seconds": 14400,
        "ingredients": {"Wild Mushroom": 10, "Kale": 5, "Wheat": 5},
        "enabled": True    },
    "Sunflower Cake": {
        "name": "Sunflower Cake",
        "building": "Bakery",
        "experience": 525,
        "cooking_seconds": 23400,
        "ingredients": {"Sunflower": 1000, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Honey Cake": {
        "name": "Honey Cake",
        "building": "Bakery",
        "experience": 4000,
        "cooking_seconds": 28800,
        "ingredients": {"Honey": 10, "Wheat": 10, "Egg": 20},
        "enabled": True    },
    "Potato Cake": {
        "name": "Potato Cake",
        "building": "Bakery",
        "experience": 650,
        "cooking_seconds": 37800,
        "ingredients": {"Potato": 500, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Pumpkin Cake": {
        "name": "Pumpkin Cake",
        "building": "Bakery",
        "experience": 625,
        "cooking_seconds": 37800,
        "ingredients": {"Pumpkin": 130, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Cornbread": {
        "name": "Cornbread",
        "building": "Bakery",
        "experience": 600,
        "cooking_seconds": 43200,
        "ingredients": {"Corn": 15, "Wheat": 5, "Egg": 10},
        "enabled": True    },
    "Carrot Cake": {
        "name": "Carrot Cake",
        "building": "Bakery",
        "experience": 750,
        "cooking_seconds": 46800,
        "ingredients": {"Carrot": 120, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Cabbage Cake": {
        "name": "Cabbage Cake",
        "building": "Bakery",
        "experience": 860,
        "cooking_seconds": 54000,
        "ingredients": {"Cabbage": 90, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Beetroot Cake": {
        "name": "Beetroot Cake",
        "building": "Bakery",
        "experience": 1250,
        "cooking_seconds": 79200,
        "ingredients": {"Beetroot": 100, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Cauliflower Cake": {
        "name": "Cauliflower Cake",
        "building": "Bakery",
        "experience": 1190,
        "cooking_seconds": 79200,
        "ingredients": {"Cauliflower": 60, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Parsnip Cake": {
        "name": "Parsnip Cake",
        "building": "Bakery",
        "experience": 1300,
        "cooking_seconds": 86400,
        "ingredients": {"Parsnip": 45, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Eggplant Cake": {
        "name": "Eggplant Cake",
        "building": "Bakery",
        "experience": 1400,
        "cooking_seconds": 86400,
        "ingredients": {"Eggplant": 30, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Radish Cake": {
        "name": "Radish Cake",
        "building": "Bakery",
        "experience": 1200,
        "cooking_seconds": 86400,
        "ingredients": {"Radish": 25, "Wheat": 10, "Egg": 30},
        "enabled": True    },
    "Wheat Cake": {
        "name": "Wheat Cake",
        "building": "Bakery",
        "experience": 1100,
        "cooking_seconds": 86400,
        "ingredients": {"Wheat": 35, "Egg": 30},
        "enabled": True    },
    "Lemon Cheesecake": {
        "name": "Lemon Cheesecake",
        "building": "Bakery",
        "experience": 30000,
        "cooking_seconds": 108000,
        "ingredients": {"Lemon": 20, "Cheese": 5, "Egg": 40},
        "enabled": True    },

    # --- GRUPO DELI ---
    "Blueberry Jam": {
        "name": "Blueberry Jam",
        "building": "Deli",
        "experience": 500,
        "cooking_seconds": 43200,
        "ingredients": {"Blueberry": 5},
        "enabled": True    },
    "Fermented Carrots": {
        "name": "Fermented Carrots",
        "building": "Deli",
        "experience": 250,
        "cooking_seconds": 86400,
        "ingredients": {"Carrot": 20},
        "enabled": True    },
    "Sauerkraut": {
        "name": "Sauerkraut",
        "building": "Deli",
        "experience": 500,
        "cooking_seconds": 86400,
        "ingredients": {"Cabbage": 20},
        "enabled": True    },
    "Fancy Fries": {
        "name": "Fancy Fries",
        "building": "Deli",
        "experience": 1000,
        "cooking_seconds": 86400,
        "ingredients": {"Sunflower": 500, "Potato": 500},
        "enabled": True    },
    "Fermented Fish": {
        "name": "Fermented Fish",
        "building": "Deli",
        "experience": 3000,
        "cooking_seconds": 86400,
        "ingredients": {"Tuna": 6},
        "enabled": True    },
    "Shroom Syrup": {
        "name": "Shroom Syrup",
        "building": "Deli",
        "experience": 10000,
        "cooking_seconds": 10,
        "ingredients": {"Magic Mushroom": 3, "Honey": 20},
        "enabled": True    },
    "Cheese": {
        "name": "Cheese",
        "building": "Deli",
        "experience": 1,
        "cooking_seconds": 1200,
        "ingredients": {"Milk": 3},
        "enabled": True    },
    "Blue Cheese": {
        "name": "Blue Cheese",
        "building": "Deli",
        "experience": 6000,
        "cooking_seconds": 10800,
        "ingredients": {"Cheese": 2, "Blueberry": 10},
        "enabled": True    },
    "Honey Cheddar": {
        "name": "Honey Cheddar",
        "building": "Deli",
        "experience": 15000,
        "cooking_seconds": 43200,
        "ingredients": {"Cheese": 3, "Honey": 5},
        "enabled": True    },

    # --- GRUPO SMOOTHIE SHACK ---
    "Purple Smoothie": {
        "name": "Purple Smoothie",
        "building": "Smoothie Shack",
        "experience": 310,
        "cooking_seconds": 1800,
        "ingredients": {"Blueberry": 5, "Cabbage": 10},
        "enabled": True    },
    "Orange Juice": {
        "name": "Orange Juice",
        "building": "Smoothie Shack",
        "experience": 375,
        "cooking_seconds": 2700,
        "ingredients": {"Orange": 5},
        "enabled": True    },
    "Apple Juice": {
        "name": "Apple Juice",
        "building": "Smoothie Shack",
        "experience": 500,
        "cooking_seconds": 3600,
        "ingredients": {"Apple": 5},
        "enabled": True    },
    "Power Smoothie": {
        "name": "Power Smoothie",
        "building": "Smoothie Shack",
        "experience": 775,
        "cooking_seconds": 5400,
        "ingredients": {"Blueberry": 10, "Kale": 5},
        "enabled": True    },
    "Bumpkin Detox": {
        "name": "Bumpkin Detox",
        "building": "Smoothie Shack",
        "experience": 975,
        "cooking_seconds": 7200,
        "ingredients": {"Apple": 5, "Orange": 5, "Carrot": 10},
        "enabled": True    },
    "Banana Blast": {
        "name": "Banana Blast",
        "building": "Smoothie Shack",
        "experience": 1200,
        "cooking_seconds": 10800,
        "ingredients": {"Banana": 10, "Egg": 10},
        "enabled": True    },
    "Grape Juice": {
        "name": "Grape Juice",
        "building": "Smoothie Shack",
        "experience": 3300,
        "cooking_seconds": 10800,
        "ingredients": {"Grape": 5, "Radish": 20},
        "enabled": True    },
    "The Lot": {
        "name": "The Lot",
        "building": "Smoothie Shack",
        "experience": 1500,
        "cooking_seconds": 12600,
        "ingredients": {"Blueberry": 1, "Orange": 1, "Grape": 1, "Apple": 1, "Banana": 1},
        "enabled": True    },
    "Carrot Juice": {
        "name": "Carrot Juice",
        "building": "Smoothie Shack",
        "experience": 200,
        "cooking_seconds": 3600,
        "ingredients": {"Carrot": 30},
        "enabled": True    },
    "Quick Juice": {
        "name": "Quick Juice",
        "building": "Smoothie Shack",
        "experience": 100,
        "cooking_seconds": 1800,
        "ingredients": {"Sunflower": 50, "Pumpkin": 40},
        "enabled": True    },
    "Slow Juice": {
        "name": "Slow Juice",
        "building": "Smoothie Shack",
        "experience": 7500,
        "cooking_seconds": 86400,
        "ingredients": {"Grape": 10, "Kale": 100},
        "enabled": True    },
    "Sour Shake": {
        "name": "Sour Shake",
        "building": "Smoothie Shack",
        "experience": 1000,
        "cooking_seconds": 3600,
        "ingredients": {"Lemon": 20},
        "enabled": True    },

    # --- GRUPO COMIDAS ESPECIAIS ---
    "Pirate Cake": {
        "name": "Pirate Cake",
        "building": "Special",
        "experience": 3000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Caponata": {
        "name": "Caponata",
        "building": "Special",
        "experience": 6000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Glazed Carrots": {
        "name": "Glazed Carrots",
        "building": "Special",
        "experience": 3000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Paella": {
        "name": "Paella",
        "building": "Special",
        "experience": 10000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Trade Cake": {
        "name": "Trade Cake",
        "building": "Special",
        "experience": 10000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },

    # --- GRUPO PEIXES (CONSUMÍVEIS) ---
    "Anchovy": {
        "name": "Anchovy",
        "building": "Fish",
        "experience": 60,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Butterflyfish": {
        "name": "Butterflyfish",
        "building": "Fish",
        "experience": 70,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Blowfish": {
        "name": "Blowfish",
        "building": "Fish",
        "experience": 80,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Clownfish": {
        "name": "Clownfish",
        "building": "Fish",
        "experience": 90,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Sea Bass": {
        "name": "Sea Bass",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Sea Horse": {
        "name": "Sea Horse",
        "building": "Fish",
        "experience": 110,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Horse Mackerel": {
        "name": "Horse Mackerel",
        "building": "Fish",
        "experience": 120,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Squid": {
        "name": "Squid",
        "building": "Fish",
        "experience": 130,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Red Snapper": {
        "name": "Red Snapper",
        "building": "Fish",
        "experience": 140,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Moray Eel": {
        "name": "Moray Eel",
        "building": "Fish",
        "experience": 150,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Olive Flounder": {
        "name": "Olive Flounder",
        "building": "Fish",
        "experience": 160,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Napoleanfish": {
        "name": "Napoleanfish",
        "building": "Fish",
        "experience": 170,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Surgeonfish": {
        "name": "Surgeonfish",
        "building": "Fish",
        "experience": 180,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Zebra Turkeyfish": {
        "name": "Zebra Turkeyfish",
        "building": "Fish",
        "experience": 190,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Ray": {
        "name": "Ray",
        "building": "Fish",
        "experience": 200,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Hammerhead shark": {
        "name": "Hammerhead shark",
        "building": "Fish",
        "experience": 210,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Barred Knifejaw": {
        "name": "Barred Knifejaw",
        "building": "Fish",
        "experience": 220,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Tuna": {
        "name": "Tuna",
        "building": "Fish",
        "experience": 230,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Mahi Mahi": {
        "name": "Mahi Mahi",
        "building": "Fish",
        "experience": 240,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Blue Marlin": {
        "name": "Blue Marlin",
        "building": "Fish",
        "experience": 250,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Oarfish": {
        "name": "Oarfish",
        "building": "Fish",
        "experience": 300,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Football fish": {
        "name": "Football fish",
        "building": "Fish",
        "experience": 350,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Sunfish": {
        "name": "Sunfish",
        "building": "Fish",
        "experience": 400,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Coelacanth": {
        "name": "Coelacanth",
        "building": "Fish",
        "experience": 700,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Whale Shark": {
        "name": "Whale Shark",
        "building": "Fish",
        "experience": 750,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Saw Shark": {
        "name": "Saw Shark",
        "building": "Fish",
        "experience": 800,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "White Shark": {
        "name": "White Shark",
        "building": "Fish",
        "experience": 1000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Angelfish": {
        "name": "Angelfish",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Halibut": {
        "name": "Halibut",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Parrotfish": {
        "name": "Parrotfish",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Porgy": {
        "name": "Porgy",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Muskellunge": {
        "name": "Muskellunge",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Trout": {
        "name": "Trout",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Walleye": {
        "name": "Walleye",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Weakfish": {
        "name": "Weakfish",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Rock Blackfish": {
        "name": "Rock Blackfish",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Cobia": {
        "name": "Cobia",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    "Tilapia": {
        "name": "Tilapia",
        "building": "Fish",
        "experience": 100,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
    
    # --- GRUPO COMIDAS DE FACÇÃO E TROCA ---
    "Caponata": {
        "name": "Caponata",
        "building": "Faction Shop",
        "experience": 6000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": False    },
    "Glazed Carrots": {
        "name": "Glazed Carrots",
        "building": "Faction Shop",
        "experience": 3000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": False    },
    "Paella": {
        "name": "Paella",
        "building": "Faction Shop",
        "experience": 10000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": False    },
    "Trade Cake": {
        "name": "Trade Cake",
        "building": "Trade",
        "experience": 10000,
        "cooking_seconds": 0,
        "ingredients": {},
        "enabled": True    },
}