# ------------------------------------------------------------------------------
# 1. BASE_DELIVERY_REWARDS: Describes all NPC base reward for delivey.
# ------------------------------------------------------------------------------

BASE_DELIVERY_REWARDS = {
    "pumpkin' pete": 1,
    "bert": 2,
    "finley": 2,
    "miranda": 2,
    "finn": 3,
    "raven": 3,
    "cornwell": 4,
    "jester": 4,
    "timmy": 4,
    "pharaoh": 5,
    "tywin": 5,
}

# ------------------------------------------------------------------------------
# 2. CHORES_BOARD_TASKS: Describes all taks to choresBoards wekkely
# ------------------------------------------------------------------------------

CHORES_BOARD_TASKS = {
    # ------------------
    # Tarefas de Colheita (Harvest)
    # ------------------
    "Harvest Sunflowers 150 times": {"requirement": 150, "activity_name": "Sunflower Harvested"},
    "Harvest Sunflowers 200 times": {"requirement": 200, "activity_name": "Sunflower Harvested"},
    "Harvest Sunflowers 250 times": {"requirement": 250, "activity_name": "Sunflower Harvested"},
    "Harvest Potatoes 100 times": {"requirement": 100, "activity_name": "Potato Harvested"},
    "Harvest Potatoes 125 times": {"requirement": 125, "activity_name": "Potato Harvested"},
    "Harvest Potatoes 130 times": {"requirement": 130, "activity_name": "Potato Harvested"},
    "Harvest Potatoes 150 times": {"requirement": 150, "activity_name": "Potato Harvested"},
    "Harvest Potatoes 200 times": {"requirement": 200, "activity_name": "Potato Harvested"},
    "Harvest Potatoes 250 times": {"requirement": 250, "activity_name": "Potato Harvested"},
    "Harvest Rhubarbs 100 times": {"requirement": 100, "activity_name": "Rhubarb Harvested"},
    "Harvest Rhubarbs 125 times": {"requirement": 125, "activity_name": "Rhubarb Harvested"},
    "Harvest Rhubarbs 150 times": {"requirement": 150, "activity_name": "Rhubarb Harvested"},
    "Harvest Pumpkins 100 times": {"requirement": 100, "activity_name": "Pumpkin Harvested"},
    "Harvest Pumpkins 130 times": {"requirement": 130, "activity_name": "Pumpkin Harvested"},
    "Harvest Pumpkins 150 times": {"requirement": 150, "activity_name": "Pumpkin Harvested"},
    "Harvest Pumpkins 200 times": {"requirement": 200, "activity_name": "Pumpkin Harvested"},
    "Harvest Pumpkins 250 times": {"requirement": 250, "activity_name": "Pumpkin Harvested"},
    "Harvest Zucchini 50 times": {"requirement": 50, "activity_name": "Zucchini Harvested"},
    "Harvest Zucchini 75 times": {"requirement": 75, "activity_name": "Zucchini Harvested"},
    "Harvest Zucchini 100 times": {"requirement": 100, "activity_name": "Zucchini Harvested"},
    "Harvest Carrots 50 times": {"requirement": 50, "activity_name": "Carrot Harvested"},
    "Harvest Carrots 60 times": {"requirement": 60, "activity_name": "Carrot Harvested"},
    "Harvest Carrots 75 times": {"requirement": 75, "activity_name": "Carrot Harvested"},
    "Harvest Carrots 100 times": {"requirement": 100, "activity_name": "Carrot Harvested"},
    "Harvest Carrots 120 times": {"requirement": 120, "activity_name": "Carrot Harvested"},
    "Harvest Yam 30 times": {"requirement": 30, "activity_name": "Yam Harvested"},
    "Harvest Yam 60 times": {"requirement": 60, "activity_name": "Yam Harvested"},
    "Harvest Yam 90 times": {"requirement": 90, "activity_name": "Yam Harvested"},
    "Harvest Yam 125 times": {"requirement": 125, "activity_name": "Yam Harvested"},
    "Harvest Yam 150 times": {"requirement": 150, "activity_name": "Yam Harvested"},
    "Harvest Yam 175 times": {"requirement": 175, "activity_name": "Yam Harvested"},
    "Harvest Cabbage 25 times": {"requirement": 25, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 30 times": {"requirement": 30, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 40 times": {"requirement": 40, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 50 times": {"requirement": 50, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 60 times": {"requirement": 60, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 75 times": {"requirement": 75, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 80 times": {"requirement": 80, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 90 times": {"requirement": 90, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 100 times": {"requirement": 100, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 125 times": {"requirement": 125, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 150 times": {"requirement": 150, "activity_name": "Cabbage Harvested"},
    "Harvest Cabbage 175 times": {"requirement": 175, "activity_name": "Cabbage Harvested"},
    "Harvest Broccoli 40 times": {"requirement": 40, "activity_name": "Broccoli Harvested"},
    "Harvest Broccoli 80 times": {"requirement": 80, "activity_name": "Broccoli Harvested"},
    "Harvest Broccoli 100 times": {"requirement": 100, "activity_name": "Broccoli Harvested"},
    "Harvest Soybeans 30 times": {"requirement": 30, "activity_name": "Soybean Harvested"},
    "Harvest Soybeans 60 times": {"requirement": 60, "activity_name": "Soybean Harvested"},
    "Harvest Soybeans 90 times": {"requirement": 90, "activity_name": "Soybean Harvested"},
    "Harvest Beetroot 30 times": {"requirement": 30, "activity_name": "Beetroot Harvested"},
    "Harvest Beetroot 50 times": {"requirement": 50, "activity_name": "Beetroot Harvested"},
    "Harvest Beetroot 60 times": {"requirement": 60, "activity_name": "Beetroot Harvested"},
    "Harvest Beetroot 75 times": {"requirement": 75, "activity_name": "Beetroot Harvested"},
    "Harvest Beetroot 90 times": {"requirement": 90, "activity_name": "Beetroot Harvested"},
    "Harvest Beetroot 100 times": {"requirement": 100, "activity_name": "Beetroot Harvested"},
    "Harvest Beetroot 120 times": {"requirement": 120, "activity_name": "Beetroot Harvested"},
    "Harvest Pepper 25 times": {"requirement": 25, "activity_name": "Pepper Harvested"},
    "Harvest Pepper 40 times": {"requirement": 40, "activity_name": "Pepper Harvested"},
    "Harvest Pepper 50 times": {"requirement": 50, "activity_name": "Pepper Harvested"},
    "Harvest Pepper 75 times": {"requirement": 75, "activity_name": "Pepper Harvested"},
    "Harvest Pepper 80 times": {"requirement": 80, "activity_name": "Pepper Harvested"},
    "Harvest Pepper 100 times": {"requirement": 100, "activity_name": "Pepper Harvested"},
    "Harvest Cauliflower 30 times": {"requirement": 30, "activity_name": "Cauliflower Harvested"},
    "Harvest Cauliflower 60 times": {"requirement": 60, "activity_name": "Cauliflower Harvested"},
    "Harvest Cauliflower 90 times": {"requirement": 90, "activity_name": "Cauliflower Harvested"},
    "Harvest Cauliflower 400 times": {"requirement": 400, "activity_name": "Cauliflower Harvested"},
    "Harvest Cauliflower 450 times": {"requirement": 450, "activity_name": "Cauliflower Harvested"},
    "Harvest Cauliflower 500 times": {"requirement": 500, "activity_name": "Cauliflower Harvested"},
    "Harvest Eggplant 300 times": {"requirement": 300, "activity_name": "Eggplant Harvested"},
    "Harvest Eggplant 360 times": {"requirement": 360, "activity_name": "Eggplant Harvested"},
    "Harvest Eggplant 420 times": {"requirement": 420, "activity_name": "Eggplant Harvested"},
    "Harvest Corn 300 times": {"requirement": 300, "activity_name": "Corn Harvested"},
    "Harvest Corn 360 times": {"requirement": 360, "activity_name": "Corn Harvested"},
    "Harvest Corn 420 times": {"requirement": 420, "activity_name": "Corn Harvested"},
    "Harvest Onions 300 times": {"requirement": 300, "activity_name": "Onion Harvested"},
    "Harvest Onions 360 times": {"requirement": 360, "activity_name": "Onion Harvested"},
    "Harvest Onions 420 times": {"requirement": 420, "activity_name": "Onion Harvested"},
    "Harvest Wheat 240 times": {"requirement": 240, "activity_name": "Wheat Harvested"},
    "Harvest Wheat 250 times": {"requirement": 250, "activity_name": "Wheat Harvested"},
    "Harvest Wheat 300 times": {"requirement": 300, "activity_name": "Wheat Harvested"},
    "Harvest Wheat 360 times": {"requirement": 360, "activity_name": "Wheat Harvested"},
    "Harvest Radish 240 times": {"requirement": 240, "activity_name": "Radish Harvested"},
    "Harvest Radish 280 times": {"requirement": 280, "activity_name": "Radish Harvested"},
    "Harvest Radish 340 times": {"requirement": 340, "activity_name": "Radish Harvested"},
    "Harvest Turnip 250 times": {"requirement": 250, "activity_name": "Turnip Harvested"},
    "Harvest Turnip 300 times": {"requirement": 300, "activity_name": "Turnip Harvested"},
    "Harvest Turnip 360 times": {"requirement": 360, "activity_name": "Turnip Harvested"},
    "Harvest Kale 120 times": {"requirement": 120, "activity_name": "Kale Harvested"},
    "Harvest Kale 180 times": {"requirement": 180, "activity_name": "Kale Harvested"},
    "Harvest Kale 200 times": {"requirement": 200, "activity_name": "Kale Harvested"},
    "Harvest Kale 240 times": {"requirement": 240, "activity_name": "Kale Harvested"},
    "Harvest Artichoke 150 times": {"requirement": 150, "activity_name": "Artichoke Harvested"},
    "Harvest Artichoke 200 times": {"requirement": 200, "activity_name": "Artichoke Harvested"},
    "Harvest Artichoke 260 times": {"requirement": 260, "activity_name": "Artichoke Harvested"},
    "Harvest Barley 100 times": {"requirement": 100, "activity_name": "Barley Harvested"},
    "Harvest Barley 120 times": {"requirement": 120, "activity_name": "Barley Harvested"},
    "Harvest Barley 150 times": {"requirement": 150, "activity_name": "Barley Harvested"},
    "Harvest Barley 180 times": {"requirement": 180, "activity_name": "Barley Harvested"},
    "Harvest Barley 200 times": {"requirement": 200, "activity_name": "Barley Harvested"},
    "Harvest Rice 16 times": {"requirement": 16, "activity_name": "Rice Harvested"},
    "Harvest Rice 20 times": {"requirement": 20, "activity_name": "Rice Harvested"},
    "Harvest Rice 24 times": {"requirement": 24, "activity_name": "Rice Harvested"},
    "Harvest Olives 12 times": {"requirement": 12, "activity_name": "Olive Harvested"},
    "Harvest Olives 16 times": {"requirement": 16, "activity_name": "Olive Harvested"},
    "Harvest Olives 20 times": {"requirement": 20, "activity_name": "Olive Harvested"},
    
    # ------------------
    # Tarefas de Alimentação (Eat)
    # ------------------
    "Eat 3 Boiled Eggs": {"requirement": 3, "activity_name": "Boiled Eggs Fed"},
    "Eat 5 Boiled Eggs": {"requirement": 5, "activity_name": "Boiled Eggs Fed"},
    "Eat 7 Boiled Eggs": {"requirement": 7, "activity_name": "Boiled Eggs Fed"},
    "Eat 10 Boiled Eggs": {"requirement": 10, "activity_name": "Boiled Eggs Fed"},
    "Eat 15 Boiled Eggs": {"requirement": 15, "activity_name": "Boiled Eggs Fed"},
    "Eat 10 Reindeer Carrot": {"requirement": 10, "activity_name": "Reindeer Carrot Fed"},
    "Eat 15 Reindeer Carrot": {"requirement": 15, "activity_name": "Reindeer Carrot Fed"},
    "Eat 20 Anchovies": {"requirement": 20, "activity_name": "Anchovy Fed"},
    "Eat 40 Anchovies": {"requirement": 40, "activity_name": "Anchovy Fed"},
    "Eat 60 Anchovies": {"requirement": 60, "activity_name": "Anchovy Fed"},
    "Eat 10 Tunas": {"requirement": 10, "activity_name": "Tuna Fed"},
    "Eat 20 Tunas": {"requirement": 20, "activity_name": "Tuna Fed"},
    "Eat 30 Tunas": {"requirement": 30, "activity_name": "Tuna Fed"},
    "Eat 5 Cauliflower Burgers": {"requirement": 5, "activity_name": "Cauliflower Burger Fed"},
    "Eat 5 Club Sandwiches": {"requirement": 5, "activity_name": "Club Sandwich Fed"},
    "Eat 5 Pancakes": {"requirement": 5, "activity_name": "Pancakes Fed"},
    "Eat 20 Chowder": {"requirement": 20, "activity_name": "Chowder Fed"},
    "Eat 25 Chowder": {"requirement": 25, "activity_name": "Chowder Fed"},
    "Eat 30 Chowder": {"requirement": 30, "activity_name": "Chowder Fed"},
    "Eat 5 Orange Cake": {"requirement": 5, "activity_name": "Orange Cake Fed"},
    "Eat 7 Orange Cake": {"requirement": 7, "activity_name": "Orange Cake Fed"},
    "Eat 10 Orange Cake": {"requirement": 10, "activity_name": "Orange Cake Fed"},
    "Eat 15 Orange Cake": {"requirement": 15, "activity_name": "Orange Cake Fed"},
    "Eat 10 Mashed Potatoes": {"requirement": 10, "activity_name": "Mashed Potato Fed"},
    "Eat 15 Mashed Potatoes": {"requirement": 15, "activity_name": "Mashed Potato Fed"},
    "Eat 20 Mashed Potatoes": {"requirement": 20, "activity_name": "Mashed Potato Fed"},
    "Eat 30 Mashed Potatoes": {"requirement": 30, "activity_name": "Mashed Potato Fed"},
    "Eat 20 Pumpkin Soup": {"requirement": 20, "activity_name": "Pumpkin Soup Fed"},
    "Eat 30 Pumpkin Soup": {"requirement": 30, "activity_name": "Pumpkin Soup Fed"},
    "Eat 5 Bumpkin Salad": {"requirement": 5, "activity_name": "Bumpkin Salad Fed"},
    "Eat 15 Pumpkin Soup": {"requirement": 15, "activity_name": "Pumpkin Soup Fed"},
    "Eat 7 Chowder": {"requirement": 7, "activity_name": "Chowder Fed"},

    # ------------------
    # Tarefas de Bebidas (Drink)
    # ------------------
    "Drink 15 Orange Juice": {"requirement": 15, "activity_name": "Orange Juice Fed"},
    "Drink 15 Purple Smoothies": {"requirement": 15, "activity_name": "Purple Smoothie Fed"},
    "Drink 10 Apple Juice": {"requirement": 10, "activity_name": "Apple Juice Fed"},
    "Drink 5 Power Smoothies": {"requirement": 5, "activity_name": "Power Smoothie Fed"},
    "Drink 25 Orange Juice": {"requirement": 25, "activity_name": "Orange Juice Fed"},
    "Drink 35 Orange Juice": {"requirement": 35, "activity_name": "Orange Juice Fed"},
    "Drink 40 Orange Juice": {"requirement": 40, "activity_name": "Orange Juice Fed"},
    "Drink 50 Orange Juice": {"requirement": 50, "activity_name": "Orange Juice Fed"},
    "Drink 15 Sour Shakes": {"requirement": 15, "activity_name": "Sour Shake Fed"},
    "Drink 15 Banana Blast": {"requirement": 15, "activity_name": "Banana Blast Fed"},
    "Drink 5 Grape Juice": {"requirement": 5, "activity_name": "Grape Juice Fed"},
    "Drink 10 Orange Juice": {"requirement": 10, "activity_name": "Orange Juice Fed"},
    "Drink 15 Carrot Juice": {"requirement": 15, "activity_name": "Carrot Juice Fed"},
    
    # ------------------
    # Tarefas de Culinária (Cook)
    # ------------------
    "Cook Boiled Eggs 3 times": {"requirement": 3, "activity_name": "Boiled Eggs Cooked"},
    "Cook Boiled Eggs 5 times": {"requirement": 5, "activity_name": "Boiled Eggs Cooked"},
    "Cook Reindeer Carrot 8 times": {"requirement": 8, "activity_name": "Reindeer Carrot Cooked"},
    "Cook Reindeer Carrot 12 times": {"requirement": 12, "activity_name": "Reindeer Carrot Cooked"},
    "Cook Mashed Potatoes 15 times": {"requirement": 15, "activity_name": "Mashed Potato Cooked"},
    "Cook Mashed Potatoes 18 times": {"requirement": 18, "activity_name": "Mashed Potato Cooked"},
    "Cook Mashed Potatoes 20 times": {"requirement": 20, "activity_name": "Mashed Potato Cooked"},
    "Cook Roast Veggies 5 times": {"requirement": 5, "activity_name": "Roast Veggies Cooked"},
    "Cook Roast Veggies 6 times": {"requirement": 6, "activity_name": "Roast Veggies Cooked"},
    "Cook Roast Veggies 7 times": {"requirement": 7, "activity_name": "Roast Veggies Cooked"},
    "Cook Club Sandwich 5 times": {"requirement": 5, "activity_name": "Club Sandwich Cooked"},
    "Cook Club Sandwich 6 times": {"requirement": 6, "activity_name": "Club Sandwich Cooked"},
    "Cook Club Sandwich 7 times": {"requirement": 7, "activity_name": "Club Sandwich Cooked"},
    "Cook Pancakes 3 times": {"requirement": 3, "activity_name": "Pancakes Cooked"},
    "Cook Pancakes 4 times": {"requirement": 4, "activity_name": "Pancakes Cooked"},
    "Cook Pancakes 5 times": {"requirement": 5, "activity_name": "Pancakes Cooked"},
    "Cook Pancakes 6 times": {"requirement": 6, "activity_name": "Pancakes Cooked"},
    "Cook Fried Calamari 1 time": {"requirement": 1, "activity_name": "Fried Calamari Cooked"},
    "Cook Fried Calamari 2 times": {"requirement": 2, "activity_name": "Fried Calamari Cooked"},
    "Cook Fried Calamari 3 times": {"requirement": 3, "activity_name": "Fried Calamari Cooked"},
    "Cook Fried Calamari 4 times": {"requirement": 4, "activity_name": "Fried Calamari Cooked"},
    "Cook Cauliflower Burger 5 times": {"requirement": 5, "activity_name": "Cauliflower Burger Cooked"},
    "Cook Cauliflower Burger 7 times": {"requirement": 7, "activity_name": "Cauliflower Burger Cooked"},
    "Cook Cauliflower Burger 10 times": {"requirement": 10, "activity_name": "Cauliflower Burger Cooked"},
    "Cook Bumpkin Salad 5 times": {"requirement": 5, "activity_name": "Bumpkin Salad Cooked"},
    "Cook Bumpkin Salad 7 times": {"requirement": 7, "activity_name": "Bumpkin Salad Cooked"},
    "Cook Bumpkin Salad 10 times": {"requirement": 10, "activity_name": "Bumpkin Salad Cooked"},
    "Cook Bumpkin ganoush 3 times": {"requirement": 3, "activity_name": "Bumpkin ganoush Cooked"},
    "Cook Bumpkin ganoush 5 times": {"requirement": 5, "activity_name": "Bumpkin ganoush Cooked"},
    "Cook Bumpkin ganoush 7 times": {"requirement": 7, "activity_name": "Bumpkin ganoush Cooked"},
    "Cook Goblin's Treat 3 times": {"requirement": 3, "activity_name": "Goblin's Treat Cooked"},
    "Cook Goblin's Treat 5 times": {"requirement": 5, "activity_name": "Goblin's Treat Cooked"},
    "Cook Goblin's Treat 7 times": {"requirement": 7, "activity_name": "Goblin's Treat Cooked"},
    "Cook Gumbo 20 times": {"requirement": 20, "activity_name": "Gumbo Cooked"},
    "Cook Gumbo 25 times": {"requirement": 25, "activity_name": "Gumbo Cooked"},
    "Cook Gumbo 30 times": {"requirement": 30, "activity_name": "Gumbo Cooked"},
    "Cook Sunflower Cake 7 times": {"requirement": 7, "activity_name": "Sunflower Cake Cooked"},
    "Cook Carrot Cake 5 times": {"requirement": 5, "activity_name": "Carrot Cake Cooked"},
    "Cook Cabbage Cake 5 times": {"requirement": 5, "activity_name": "Cabbage Cake Cooked"},
    "Cook Wheat Cake 5 times": {"requirement": 5, "activity_name": "Wheat Cake Cooked"},
    "Cook Honey Cake 10 times": {"requirement": 10, "activity_name": "Honey Cake Cooked"},
    "Cook Honey Cake 15 times": {"requirement": 15, "activity_name": "Honey Cake Cooked"},
    "Cook Honey Cake 20 times": {"requirement": 20, "activity_name": "Honey Cake Cooked"},
    "Cook Cornbread 10 times": {"requirement": 10, "activity_name": "Cornbread Cooked"},
    "Cook Lemon Cheesecakes 3 times": {"requirement": 3, "activity_name": "Lemon Cheesecake Cooked"},
    "Cook Lemon Cheesecakes 5 times": {"requirement": 5, "activity_name": "Lemon Cheesecake Cooked"},
    "Cook Fermented Fish 10 times": {"requirement": 10, "activity_name": "Fermented Fish Cooked"},
    "Cook Fermented Fish 12 times": {"requirement": 12, "activity_name": "Fermented Fish Cooked"},
    "Cook Fermented Fish 15 times": {"requirement": 15, "activity_name": "Fermented Fish Cooked"},
    "Cook Chowder 15 times": {"requirement": 15, "activity_name": "Chowder Cooked"},
    "Cook Chowder 18 times": {"requirement": 18, "activity_name": "Chowder Cooked"},
    "Cook Chowder 21 times": {"requirement": 21, "activity_name": "Chowder Cooked"},
    "Cook Antipasto 25 times": {"requirement": 25, "activity_name": "Antipasto Cooked"},
    "Cook Antipasto 30 times": {"requirement": 30, "activity_name": "Antipasto Cooked"},
    "Cook Antipasto 35 times": {"requirement": 35, "activity_name": "Antipasto Cooked"},
    "Cook Fruit Salad 50 times": {"requirement": 50, "activity_name": "Fruit Salad Cooked"},
    "Cook Fruit Salad 75 times": {"requirement": 75, "activity_name": "Fruit Salad Cooked"},
    "Cook Fruit Salad 100 times": {"requirement": 100, "activity_name": "Fruit Salad Cooked"},
    "Cook Steamed Red Rice 20 times": {"requirement": 20, "activity_name": "Steamed Red Rice Cooked"},
    "Cook Steamed Red Rice 25 times": {"requirement": 25, "activity_name": "Steamed Red Rice Cooked"},
    "Cook Steamed Red Rice 30 times": {"requirement": 30, "activity_name": "Steamed Red Rice Cooked"},
    "Cook Rice Bun 20 times": {"requirement": 20, "activity_name": "Rice Bun Cooked"},
    "Cook Rice Bun 25 times": {"requirement": 25, "activity_name": "Rice Bun Cooked"},
    "Cook Rice Bun 30 times": {"requirement": 30, "activity_name": "Rice Bun Cooked"},
    "Cook Shroom Syrup 2 times": {"requirement": 2, "activity_name": "Shroom Syrup Cooked"},
    "Cook Cheese 50 times": {"requirement": 50, "activity_name": "Cheese Cooked"},
    "Cook Honey Cheddar 5 times": {"requirement": 5, "activity_name": "Honey Cheddar Cooked"},
    "Cook Honey Cheddar 7 times": {"requirement": 7, "activity_name": "Honey Cheddar Cooked"},
    "Cook Honey Cheddar 10 times": {"requirement": 10, "activity_name": "Honey Cheddar Cooked"},
    "Cook Blue Cheese 20 times": {"requirement": 20, "activity_name": "Blue Cheese Cooked"},
    "Cook Blue Cheese 25 times": {"requirement": 25, "activity_name": "Blue Cheese Cooked"},
    "Cook Blue Cheese 30 times": {"requirement": 30, "activity_name": "Blue Cheese Cooked"},
    "Cook Goblin Brunch 1 time": {"requirement": 1, "activity_name": "Goblin Brunch Cooked"},
    "Cook Goblin Brunch 2 times": {"requirement": 2, "activity_name": "Goblin Brunch Cooked"},
    "Cook Goblin Brunch 3 times": {"requirement": 3, "activity_name": "Goblin Brunch Cooked"},
    "Cook Sushi Roll 3 times": {"requirement": 3, "activity_name": "Sushi Roll Cooked"},
    "Cook Sushi Roll 4 times": {"requirement": 4, "activity_name": "Sushi Roll Cooked"},
    "Cook Sushi Roll 5 times": {"requirement": 5, "activity_name": "Sushi Roll Cooked"},
    "Cook Caprese Salad 4 times": {"requirement": 4, "activity_name": "Caprese Salad Cooked"},
    "Cook Caprese Salad 5 times": {"requirement": 5, "activity_name": "Caprese Salad Cooked"},
    "Cook Caprese Salad 6 times": {"requirement": 6, "activity_name": "Caprese Salad Cooked"},
    "Cook Caprese Salad 7 times": {"requirement": 7, "activity_name": "Caprese Salad Cooked"},
    "Cook Caprese Salad 8 times": {"requirement": 8, "activity_name": "Caprese Salad Cooked"},
    "Cook Caprese Salad 10 times": {"requirement": 10, "activity_name": "Caprese Salad Cooked"},
    "Cook Ocean's Olive 3 times": {"requirement": 3, "activity_name": "Ocean's Olive Cooked"},
    "Cook Ocean's Olive 5 times": {"requirement": 5, "activity_name": "Ocean's Olive Cooked"},
    "Cook Ocean's Olive 7 times": {"requirement": 7, "activity_name": "Ocean's Olive Cooked"},
    "Cook Eggplant Cake 5 times": {"requirement": 5, "activity_name": "Eggplant Cake Cooked"},
    "Cook Radish Cake 5 times": {"requirement": 5, "activity_name": "Radish Cake Cooked"},
    "Cook Beetroot Cake 5 times": {"requirement": 5, "activity_name": "Beetroot Cake Cooked"},
    "Cook Pumpkin Soup 5 times": {"requirement": 5, "activity_name": "Pumpkin Soup Cooked"},
    "Cook Pumpkin Soup 7 times": {"requirement": 7, "activity_name": "Pumpkin Soup Cooked"},
    "Cook Pumpkin Soup 10 times": {"requirement": 10, "activity_name": "Pumpkin Soup Cooked"},
    "Cook Bumpkin Roast 5 times": {"requirement": 5, "activity_name": "Bumpkin Roast Cooked"},
    "Cook Bumpkin Roast 7 times": {"requirement": 7, "activity_name": "Bumpkin Roast Cooked"},
    "Cook Bumpkin Roast 10 times": {"requirement": 10, "activity_name": "Bumpkin Roast Cooked"},
    "Cook Pizza Margherita 5 times": {"requirement": 5, "activity_name": "Pizza Margherita Cooked"},
    "Cook Pizza Margherita 7 times": {"requirement": 7, "activity_name": "Pizza Margherita Cooked"},
    "Cook Pizza Margherita 10 times": {"requirement": 10, "activity_name": "Pizza Margherita Cooked"},
    "Cook Apple Pie 15 times": {"requirement": 15, "activity_name": "Apple Pie Cooked"},
    "Cook Potato Cake 7 times": {"requirement": 7, "activity_name": "Potato Cake Cooked"},
    "Cook Carrot Cake 7 times": {"requirement": 7, "activity_name": "Carrot Cake Cooked"},
    "Cook Wheat Cake 7 times": {"requirement": 7, "activity_name": "Wheat Cake Cooked"},
    "Cook Spaghetti al Limone 4 times": {"requirement": 4, "activity_name": "Spaghetti al Limone Cooked"},
    "Cook Spaghetti al Limone 6 times": {"requirement": 6, "activity_name": "Spaghetti al Limone Cooked"},
    "Cook Spaghetti al Limone 8 times": {"requirement": 8, "activity_name": "Spaghetti al Limone Cooked"},
    "Cook Beetroot Cake 7 times": {"requirement": 7, "activity_name": "Beetroot Cake Cooked"},
    "Cook Cabbage Cake 7 times": {"requirement": 7, "activity_name": "Cabbage Cake Cooked"},
    "Cook Parsnip Cake 7 times": {"requirement": 7, "activity_name": "Parsnip Cake Cooked"},
    "Cook Cauliflower Cake 7 times": {"requirement": 7, "activity_name": "Cauliflower Cake Cooked"},
    "Cook 5 Fermented Fish": {"requirement": 5, "activity_name": "Fermented Fish Cooked"},
    "Cook 10 Sushi Roll": {"requirement": 10, "activity_name": "Sushi Roll Cooked"},

    # ------------------
    # Tarefas de Preparo (Smoothies)
    # ------------------
    "Prepare Power Smoothie 20 times": {"requirement": 20, "activity_name": "Power Smoothie Cooked"},
    "Prepare Power Smoothie 35 times": {"requirement": 35, "activity_name": "Power Smoothie Cooked"},
    "Prepare Power Smoothie 50 times": {"requirement": 50, "activity_name": "Power Smoothie Cooked"},
    "Prepare Slow Juice 5 times": {"requirement": 5, "activity_name": "Slow Juice Cooked"},
    "Prepare Slow Juice 6 times": {"requirement": 6, "activity_name": "Slow Juice Cooked"},
    "Prepare Slow Juice 7 times": {"requirement": 7, "activity_name": "Slow Juice Cooked"},
    "Prepare Banana Blast 20 times": {"requirement": 20, "activity_name": "Banana Blast Cooked"},
    "Prepare Banana Blast 35 times": {"requirement": 35, "activity_name": "Banana Blast Cooked"},
    "Prepare Banana Blast 50 times": {"requirement": 50, "activity_name": "Banana Blast Cooked"},
    "Prepare Grape Juice 10 times": {"requirement": 10, "activity_name": "Grape Juice Cooked"},
    "Prepare Grape Juice 12 times": {"requirement": 12, "activity_name": "Grape Juice Cooked"},
    "Prepare Grape Juice 15 times": {"requirement": 15, "activity_name": "Grape Juice Cooked"},
    "Prepare Apple Juice 5 times": {"requirement": 5, "activity_name": "Apple Juice Cooked"},
    "Prepare Apple Juice 6 times": {"requirement": 6, "activity_name": "Apple Juice Cooked"},
    "Prepare Apple Juice 7 times": {"requirement": 7, "activity_name": "Apple Juice Cooked"},
    "Prepare Apple Juice 15 times": {"requirement": 15, "activity_name": "Apple Juice Cooked"},
    "Prepare Apple Juice 20 times": {"requirement": 20, "activity_name": "Apple Juice Cooked"},
    "Prepare Apple Juice 25 times": {"requirement": 25, "activity_name": "Apple Juice Cooked"},
    "Prepare Carrot Juice 2 times": {"requirement": 2, "activity_name": "Carrot Juice Cooked"},
    "Prepare Carrot Juice 3 times": {"requirement": 3, "activity_name": "Carrot Juice Cooked"},
    "Prepare Carrot Juice 4 times": {"requirement": 4, "activity_name": "Carrot Juice Cooked"},
    "Prepare Purple Smoothie 5 times": {"requirement": 5, "activity_name": "Purple Smoothie Cooked"},
    "Prepare Purple Smoothie 6 times": {"requirement": 6, "activity_name": "Purple Smoothie Cooked"},
    "Prepare Purple Smoothie 7 times": {"requirement": 7, "activity_name": "Purple Smoothie Cooked"},
    "Prepare Power Smoothie 2 times": {"requirement": 2, "activity_name": "Power Smoothie Cooked"},
    "Prepare Power Smoothie 3 times": {"requirement": 3, "activity_name": "Power Smoothie Cooked"},
    "Prepare Power Smoothie 4 times": {"requirement": 4, "activity_name": "Power Smoothie Cooked"},
    "Prepare 15 Bumpkin Detox": {"requirement": 15, "activity_name": "Bumpkin Detox Cooked"},

    # ------------------
    # Tarefas de Cultivo de Flores (Grow)
    # ------------------
    "Grow Red Pansy 2 times": {"requirement": 2, "activity_name": "Red Pansy Harvested"},
    "Grow Red Pansy 3 times": {"requirement": 3, "activity_name": "Red Pansy Harvested"},
    "Grow Yellow Pansy 2 times": {"requirement": 2, "activity_name": "Yellow Pansy Harvested"},
    "Grow Yellow Pansy 3 times": {"requirement": 3, "activity_name": "Yellow Pansy Harvested"},
    "Grow Purple Cosmos 2 times": {"requirement": 2, "activity_name": "Purple Cosmos Harvested"},
    "Grow Purple Cosmos 3 times": {"requirement": 3, "activity_name": "Purple Cosmos Harvested"},
    "Grow Blue Cosmos 2 times": {"requirement": 2, "activity_name": "Blue Cosmos Harvested"},
    "Grow Blue Cosmos 3 times": {"requirement": 3, "activity_name": "Blue Cosmos Harvested"},
    "Grow Red Balloon Flower 3 times": {"requirement": 3, "activity_name": "Red Balloon Flower Harvested"},
    "Grow Red Balloon Flower 4 times": {"requirement": 4, "activity_name": "Red Balloon Flower Harvested"},
    "Grow Red Balloon Flower 5 times": {"requirement": 5, "activity_name": "Red Balloon Flower Harvested"},
    "Grow Red Balloon Flower 6 times": {"requirement": 6, "activity_name": "Red Balloon Flower Harvested"},
    "Grow Blue Balloon Flower 3 times": {"requirement": 3, "activity_name": "Blue Balloon Flower Harvested"},
    "Grow Blue Balloon Flower 4 times": {"requirement": 4, "activity_name": "Blue Balloon Flower Harvested"},
    "Grow Blue Balloon Flower 5 times": {"requirement": 5, "activity_name": "Blue Balloon Flower Harvested"},
    "Grow Purple Daffodil 3 times": {"requirement": 3, "activity_name": "Purple Daffodil Harvested"},
    "Grow Purple Daffodil 4 times": {"requirement": 4, "activity_name": "Purple Daffodil Harvested"},
    "Grow Purple Daffodil 5 times": {"requirement": 5, "activity_name": "Purple Daffodil Harvested"},
    "Grow Purple Daffodil 6 times": {"requirement": 6, "activity_name": "Purple Daffodil Harvested"},
    "Grow Red Daffodil 2 times": {"requirement": 2, "activity_name": "Red Daffodil Harvested"},
    "Grow Red Daffodil 3 times": {"requirement": 3, "activity_name": "Red Daffodil Harvested"},
    "Grow Yellow Carnation 3 times": {"requirement": 3, "activity_name": "Yellow Carnation Harvested"},
    "Grow Blue Carnation 3 times": {"requirement": 3, "activity_name": "Blue Carnation Harvested"},
    "Grow White Carnation 3 times": {"requirement": 3, "activity_name": "White Carnation Harvested"},
    "Grow Red Lotus 3 times": {"requirement": 3, "activity_name": "Red Lotus Harvested"},
    "Grow Yellow Lotus 3 times": {"requirement": 3, "activity_name": "Yellow Lotus Harvested"},
    "Grow White Lotus 3 times": {"requirement": 3, "activity_name": "White Lotus Harvested"},
    "Grow Blue Pansy 6 times": {"requirement": 6, "activity_name": "Blue Pansy Harvested"},
    "Grow White Pansy 6 times": {"requirement": 6, "activity_name": "White Pansy Harvested"},
    "Grow White Pansy 3 times": {"requirement": 3, "activity_name": "White Pansy Harvested"},
    "Grow White Cosmos 3 times": {"requirement": 3, "activity_name": "White Cosmos Harvested"},

    # ------------------
    # Tarefas de Pesca (Fish)
    # ------------------
    "Fish 20 times": {"requirement": 20, "activity_name": "Rod Casted"},
    "Fish 40 times": {"requirement": 40, "activity_name": "Rod Casted"},
    "Fish 60 times": {"requirement": 60, "activity_name": "Rod Casted"},
    "Fish 200 times": {"requirement": 200, "activity_name": "Rod Casted"},
    "Fish 250 times": {"requirement": 250, "activity_name": "Rod Casted"},
    "Fish 275 times": {"requirement": 275, "activity_name": "Rod Casted"},

    # ------------------
    # Tarefas de Fabrico (Craft)
    # ------------------
    "Craft 10 Axes": {"requirement": 10, "activity_name": "Axe Crafted"},
    "Craft 12 Axes": {"requirement": 12, "activity_name": "Axe Crafted"},
    "Craft 15 Axes": {"requirement": 15, "activity_name": "Axe Crafted"},
    "Craft 6 Pickaxes": {"requirement": 6, "activity_name": "Pickaxe Crafted"},
    "Craft 8 Pickaxes": {"requirement": 8, "activity_name": "Pickaxe Crafted"},
    "Craft 10 Pickaxes": {"requirement": 10, "activity_name": "Pickaxe Crafted"},
    "Craft 100 Rods": {"requirement": 100, "activity_name": "Rod Crafted"},
    "Craft 150 Rods": {"requirement": 150, "activity_name": "Rod Crafted"},
    "Craft 200 Rods": {"requirement": 200, "activity_name": "Rod Crafted"},
    "Craft 25 Gold Pickaxes": {"requirement": 25, "activity_name": "Gold Pickaxe Crafted"},
    "Craft 30 Gold Pickaxes": {"requirement": 30, "activity_name": "Gold Pickaxe Crafted"},
    "Craft 35 Gold Pickaxes": {"requirement": 35, "activity_name": "Gold Pickaxe Crafted"},
    "Craft 40 Gold Pickaxes": {"requirement": 40, "activity_name": "Gold Pickaxe Crafted"},
    "Craft 5 Sand Drill": {"requirement": 5, "activity_name": "Sand Drill Crafted"},
    "Craft 10 Sand Drill": {"requirement": 10, "activity_name": "Sand Drill Crafted"},
    "Craft 15 Sand Drill": {"requirement": 15, "activity_name": "Sand Drill Crafted"},

    # ------------------
    # Tarefas de Lenhador (Chop)
    # ------------------
    "Chop Trees 10 times": {"requirement": 10, "activity_name": "Tree Chopped"},
    "Chop Trees 15 times": {"requirement": 15, "activity_name": "Tree Chopped"},
    "Chop Trees 20 times": {"requirement": 20, "activity_name": "Tree Chopped"},
    "Chop Trees 100 times": {"requirement": 100, "activity_name": "Tree Chopped"},
    "Chop Trees 120 times": {"requirement": 120, "activity_name": "Tree Chopped"},
    "Chop Trees 150 times": {"requirement": 150, "activity_name": "Tree Chopped"},
    "Chop Trees 450 times": {"requirement": 450, "activity_name": "Tree Chopped"},
    "Chop Trees 500 times": {"requirement": 500, "activity_name": "Tree Chopped"},
    "Chop Trees 600 times": {"requirement": 600, "activity_name": "Tree Chopped"},
    "Chop 80 Trees": {"requirement": 80, "activity_name": "Tree Chopped"},

    # ------------------
    # Tarefas de Mineração (Mine)
    # ------------------
    "Mine Stones 5 times": {"requirement": 5, "activity_name": "Stone Mined"},
    "Mine Stones 7 times": {"requirement": 7, "activity_name": "Stone Mined"},
    "Mine Stones 8 times": {"requirement": 8, "activity_name": "Stone Mined"},
    "Mine Stones 50 times": {"requirement": 50, "activity_name": "Stone Mined"},
    "Mine Stones 60 times": {"requirement": 60, "activity_name": "Stone Mined"},
    "Mine Stones 100 times": {"requirement": 100, "activity_name": "Stone Mined"},
    "Mine Gold 30 times": {"requirement": 30, "activity_name": "Gold Mined"},
    "Mine Gold 38 times": {"requirement": 38, "activity_name": "Gold Mined"},
    "Mine Gold 45 times": {"requirement": 45, "activity_name": "Gold Mined"},
    "Mine Crimstone 20 times": {"requirement": 20, "activity_name": "Crimstone Mined"},
    "Mine Crimstone 22 times": {"requirement": 22, "activity_name": "Crimstone Mined"},
    "Mine Crimstone 24 times": {"requirement": 24, "activity_name": "Crimstone Mined"},
    "Mine Iron 150 times": {"requirement": 150, "activity_name": "Iron Mined"},
    "Mine Iron 175 times": {"requirement": 175, "activity_name": "Iron Mined"},
    "Mine Iron 200 times": {"requirement": 200, "activity_name": "Iron Mined"},
    "Mine Iron 225 times": {"requirement": 225, "activity_name": "Iron Mined"},
    "Mine Stones 200 times": {"requirement": 200, "activity_name": "Stone Mined"},
    "Mine Stones 250 times": {"requirement": 250, "activity_name": "Stone Mined"},
    "Mine Stones 300 times": {"requirement": 300, "activity_name": "Stone Mined"},
    "Mine 10 Crimstone": {"requirement": 10, "activity_name": "Crimstone Mined"},

    # ------------------
    # Tarefas de Perfuração (Drill)
    # ------------------
    "Drill Oil Reserves 15 times": {"requirement": 15, "activity_name": "Oil Drilled"},
    "Drill Oil Reserves 18 times": {"requirement": 18, "activity_name": "Oil Drilled"},
    "Drill Oil Reserves 21 times": {"requirement": 21, "activity_name": "Oil Drilled"},

    # ------------------
    # Tarefas de Colheita de Frutas (Pick)
    # ------------------
    "Pick Blueberries 120 times": {"requirement": 120, "activity_name": "Blueberry Harvested"},
    "Pick Blueberries 150 times": {"requirement": 150, "activity_name": "Blueberry Harvested"},
    "Pick Blueberries 200 times": {"requirement": 200, "activity_name": "Blueberry Harvested"},
    "Pick Oranges 100 times": {"requirement": 100, "activity_name": "Orange Harvested"},
    "Pick Oranges 125 times": {"requirement": 125, "activity_name": "Orange Harvested"},
    "Pick Oranges 160 times": {"requirement": 160, "activity_name": "Orange Harvested"},
    "Pick Apples 60 times": {"requirement": 60, "activity_name": "Apple Harvested"},
    "Pick Apples 75 times": {"requirement": 75, "activity_name": "Apple Harvested"},
    "Pick Apples 90 times": {"requirement": 90, "activity_name": "Apple Harvested"},
    "Pick Tomatoes 150 times": {"requirement": 150, "activity_name": "Tomato Harvested"},
    "Pick Tomatoes 200 times": {"requirement": 200, "activity_name": "Tomato Harvested"},
    "Pick Tomatoes 250 times": {"requirement": 250, "activity_name": "Tomato Harvested"},
    "Pick Grapes 36 times": {"requirement": 36, "activity_name": "Grape Harvested"},
    "Pick Grapes 44 times": {"requirement": 44, "activity_name": "Grape Harvested"},
    "Pick Grapes 52 times": {"requirement": 52, "activity_name": "Grape Harvested"},
    "Pick Bananas 80 times": {"requirement": 80, "activity_name": "Banana Harvested"},
    "Pick Bananas 90 times": {"requirement": 90, "activity_name": "Banana Harvested"},
    "Pick Bananas 100 times": {"requirement": 100, "activity_name": "Banana Harvested"},
    "Pick Bananas 120 times": {"requirement": 120, "activity_name": "Banana Harvested"},
    "Pick Bananas 150 times": {"requirement": 150, "activity_name": "Banana Harvested"},
    "Pick Lemons 150 times": {"requirement": 150, "activity_name": "Lemon Harvested"},
    "Pick Lemons 200 times": {"requirement": 200, "activity_name": "Lemon Harvested"},
    "Pick Lemons 250 times": {"requirement": 250, "activity_name": "Lemon Harvested"},
    "Pick 60 Blueberries": {"requirement": 60, "activity_name": "Blueberry Harvested"},

    # ------------------
    # Tarefas de Coleta (Collect)
    # ------------------
    "Collect 15 Honey": {"requirement": 15, "activity_name": "Honey Harvested"},
    "Collect 18 Honey": {"requirement": 18, "activity_name": "Honey Harvested"},
    "Collect 21 Honey": {"requirement": 21, "activity_name": "Honey Harvested"},
    "Collect Eggs 60 times": {"requirement": 60, "activity_name": "Egg Collected"},
    "Collect Eggs 80 times": {"requirement": 80, "activity_name": "Egg Collected"},
    "Collect Eggs 100 times": {"requirement": 100, "activity_name": "Egg Collected"},
    "Collect Eggs 125 times": {"requirement": 125, "activity_name": "Egg Collected"},
    "Collect Eggs 150 times": {"requirement": 150, "activity_name": "Egg Collected"},
    "Collect Wool 30 times": {"requirement": 30, "activity_name": "Wool Collected"},
    "Collect Wool 40 times": {"requirement": 40, "activity_name": "Wool Collected"},
    "Collect Wool 50 times": {"requirement": 50, "activity_name": "Wool Collected"},
    "Collect Wool 60 times": {"requirement": 60, "activity_name": "Wool Collected"},
    "Collect Wool 75 times": {"requirement": 75, "activity_name": "Wool Collected"},
    "Collect Milk 30 times": {"requirement": 30, "activity_name": "Milk Collected"},
    "Collect Milk 40 times": {"requirement": 40, "activity_name": "Milk Collected"},
    "Collect Milk 50 times": {"requirement": 50, "activity_name": "Milk Collected"},
    "Collect Milk 60 times": {"requirement": 60, "activity_name": "Milk Collected"},
    "Collect Milk 75 times": {"requirement": 75, "activity_name": "Milk Collected"},
    
    # ------------------
    # Tarefas de Escavação (Dig)
    # ------------------
    "Dig 50 times": {"requirement": 50, "activity_name": "Treasure Dug"},
    "Dig 75 times": {"requirement": 75, "activity_name": "Treasure Dug"},
    "Dig 100 times": {"requirement": 100, "activity_name": "Treasure Dug"},
    "Dig 125 times": {"requirement": 125, "activity_name": "Treasure Dug"},
    "Dig 150 times": {"requirement": 150, "activity_name": "Treasure Dug"},
    "Dig 175 times": {"requirement": 175, "activity_name": "Treasure Dug"},
    "Dig 200 times": {"requirement": 200, "activity_name": "Treasure Dug"},
    "Dig 225 times": {"requirement": 225, "activity_name": "Treasure Dug"},

    # ------------------
    # Tarefas de Gastos (Spend)
    # ------------------
    "Spend 32,000 Coins": {"requirement": 32000, "activity_name": "Coins Spent"},
    "Spend 48,000 Coins": {"requirement": 48000, "activity_name": "Coins Spent"},
    "Spend 64,000 Coins": {"requirement": 64000, "activity_name": "Coins Spent"},
}